### ISSUE TITLE
ERROR undefined

### ISSUE THREAD

**Issue by mdk3** [emanuelchristo/movie-night#1]
I get an error 
ERROR Undefined

buttons on the page are not clickable

I installed the server and wrote the ip addresses where necessary.

**Comment by emanuelchristo** [comment]
Sorry for the late reply. I hope the error was resolved. If not, please give more context.

**Comment by iamthenewking** [comment]
@mdk3 I'm having the same issue. Did you resolve this?

**Comment by mdk3** [comment]
> @mdk3 I'm having the same issue. Did you resolve this?

Yes

**Comment by emanuelchristo** [comment]
I would like to know where the error is being logged. Is it in the client side or server side? (A screenshot would be great). And by buttons, if you mean the audio chat buttons, they are not implemented yet. It is just the UI elements for now. The entire project is being rewritten from scratch using React/Next.js for the frontend and Node.js and associated media streaming servers for the backend. The new project will have a lot more features like file streaming, video chat, text chat, screen share etc. That repo is still under development.

**Comment by mdk3** [comment]
I didn't mean voice chat, the error I got at the beginning was valid for all buttons, but I solved the problem, can you help me how can we message?

**Comment by mdk3** [comment]
i think the problem is caused by npm version

**Comment by mdk3** [comment]
I don't remember exactly, but when I clicked on the buttons on the client, I was getting the error I wrote on the server and nothing was working.

**Comment by emanuelchristo** [comment]
the ERROR undefined shown in the frontend command line is when some error occurs in the browser. You can open the browser console in the dev tools and see the error. I think the error is because you are either not running the server or is not getting connected to it. 

**Running the server**
In order to run the server, git clone the server repo https://github.com/emanuelchristo/movie-night-server and run it with 
`npm run dev` for development or `npm run start` for production. You have to set the `PORT` env var to use a custom port or it will default to port 5300 (as in the latest commit)

**Running the frontend**
In order to run the frontend, git clone the frontend repo https://github.com/emanuelchristo/movie-night and run it with `npm run dev` for development or `npm run start` for production. Make sure to set the `SERVER_URL` env var to the url of the server or it will default to `http://localhost:5300` If you have difficulty setting up the server use a already hosted server using this URL: `https://movie-night-cris.herokuapp.com/`

**Commands to run with env vars**
Run server with custom port
`PORT=3210 npm run dev`
Run frontend with custom server url
`SERVER_URL=https://movie-night-cris.herokuapp.com/ npm run dev`

**Comment by iamthenewking** [comment]
> the ERROR undefined shown in the frontend command line is when some error occurs in the browser. You can open the browser console in the dev tools and see the error. I think the error is because you are either not running the server or is not getting connected to it.
> 
> **Running the server** In order to run the server, git clone the server repo https://github.com/emanuelchristo/movie-night-server and run it with `npm run dev` for development or `npm run start` for production. You have to set the `PORT` env var to use a custom port or it will default to port 5300 (as in the latest commit)
> 
> **Running the frontend** In order to run the frontend, git clone the frontend repo https://github.com/emanuelchristo/movie-night and run it with `npm run dev` for development or `npm run start` for production. Make sure to set the `SERVER_URL` env var to the url of the server or it will default to `http://localhost:5300` If you have difficulty setting up the server use a already hosted server using this URL: `https://movie-night-cris.herokuapp.com/`
> 
> **Commands to run with env vars** Run server with custom port `PORT=3210 npm run dev` Run frontend with custom server url `SERVER_URL=https://movie-night-cris.herokuapp.com/ npm run dev`




i will try this one more time,,,,i will get back soon .. thank you

**Comment by iamthenewking** [comment]
> the ERROR undefined shown in the frontend command line is when some error occurs in the browser. You can open the browser console in the dev tools and see the error. I think the error is because you are either not running the server or is not getting connected to it.
> 
> **Running the server** In order to run the server, git clone the server repo https://github.com/emanuelchristo/movie-night-server and run it with `npm run dev` for development or `npm run start` for production. You have to set the `PORT` env var to use a custom port or it will default to port 5300 (as in the latest commit)
> 
> **Running the frontend** In order to run the frontend, git clone the frontend repo https://github.com/emanuelchristo/movie-night and run it with `npm run dev` for development or `npm run start` for production. Make sure to set the `SERVER_URL` env var to the url of the server or it will default to `http://localhost:5300` If you have difficulty setting up the server use a already hosted server using this URL: `https://movie-night-cris.herokuapp.com/`
> 
> **Commands to run with env vars** Run server with custom port `PORT=3210 npm run dev` Run frontend with custom server url `SERVER_URL=https://movie-night-cris.herokuapp.com/ npm run dev`




i followed everything but still getting errors


here my setup 
![Screenshot 2022-02-02 234724](https://user-images.githubusercontent.com/7221308/152188623-bd69c94c-899e-461c-9d23-4fec683efe44.png)
![Screenshot 2022-02-02 234758](https://user-images.githubusercontent.com/7221308/152188662-33a33a11-e74d-48c2-8f83-5d652df21467.png)
![Screenshot 2022-02-02 235001](https://user-images.githubusercontent.com/7221308/152188675-724f3cdf-1397-4166-897c-891567430e41.png)

- Node  v17.4.0
- npm -v  8.3.1

**Comment by emanuelchristo** [comment]
This looks like a node version 17 issue. https://github.com/vercel/next.js/issues/30296
Try using node v14, 15 or 16.
Or try running with env var set using this command
`export NODE_OPTIONS=--openssl-legacy-provider` then run `npm run dev`
It is better to downgrade node version

**Comment by emanuelchristo** [comment]
On a different note.. What is that theme you are using

**Comment by iamthenewking** [comment]
already done this part

export NODE_OPTIONS=--openssl-legacy-provider then run npm run dev

the SSL is gone but I'm still having errors


I will try to downgrade node... thanks




VSCode theme : https://marketplace.visualstudio.com/items?itemName=VictoriaDrake.kabukicho   😊

**Comment by iamthenewking** [comment]
![image](https://user-images.githubusercontent.com/7221308/152204866-4e87e35f-1d83-40ed-bc02-18cdac9ff263.png)
![image](https://user-images.githubusercontent.com/7221308/152204947-b1ea4262-6ae9-47ce-993e-75a7e4d6f7dc.png)



I'm still getting errors

**Comment by emanuelchristo** [comment]
ERROR undefined is fine. It could be because of multiple reasons. To see that error you have to check the browser console. What is it saying now?

**Comment by iamthenewking** [comment]
here bro

![image](https://user-images.githubusercontent.com/7221308/152207189-a285ff35-1946-4239-ab7d-0fbc7e0ba906.png)

**Comment by emanuelchristo** [comment]
In the latest commit I've used es6 import instead of CommonJS require for importing socket io. This should have fixed the problem. Pull the latest commit and try it out. 

Make sure to run the server or use this hosted server `SERVER_URL=https://movie-night-cris.herokuapp.com/ npm run dev` or socket io will give connection errors

**Comment by iamthenewking** [comment]
> SERVER_URL=https://movie-night-cris.herokuapp.com/ npm run dev



i was able to run the frontend without issues except this error


thanks for the assistance

![image](https://user-images.githubusercontent.com/7221308/152225824-3a507721-7d24-4fe2-b6c0-89fb2c4e8d11.png)

**Comment by emanuelchristo** [comment]
Set the server url to `https://movie-night-cris.herokuapp.com` without the slash `/` at the end. Then it should work fine

**Comment by iamthenewking** [comment]
> Set the server url to `https://movie-night-cris.herokuapp.com` without the slash `/` at the end. Then it should work fine

thank you....

**Comment by iamthenewking** [comment]
I have another question...are you getting 404 response when I go back to the room ( copy and browse the the created room) this this from the dist folder using yarn generate ( live server)
